DROP TABLE Company ;
DROP TABLE GICS ;
DROP TABLE Position ;
DROP TABLE Requires ;
DROP TABLE Job ;
DROP TABLE Works ;
DROP TABLE Skill ;
DROP TABLE Person ;
DROP TABLE Course ;
DROP TABLE Section ;
DROP TABLE Has_Skill ;
DROP TABLE Teaches;
DROP TABLE Takes;



